### ISSUE TITLE
npm ERR! 401 Unauthorized: parse-passwd@latest

### ISSUE THREAD

**Issue by tiloreboucas** [doowb/parse-passwd#1]
`$ npm i parse-passwd`

`npm ERR! code E401`

`npm ERR! 401 Unauthorized: parse-passwd@latest`

`npm -v
6.4.1
`

`node -v
v10.3.0
`

**Comment by doowb** [comment]
This is probably an issue with `npm` since `parse-passwd` is available publicly. I don't think there's anything I can do from my end.
